# Generated by Django 6.0.5 on 2026-06-02 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_comment_like'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_at']},
        ),
    ]
