# Generated by Django 6.0.5 on 2026-06-04 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_book_views_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='book_covers/', verbose_name='Kitap Kapağı'),
        ),
        migrations.AddField(
            model_name='book',
            name='current_page',
            field=models.PositiveIntegerField(default=0, verbose_name='Okunan Sayfa'),
        ),
        migrations.AddField(
            model_name='book',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Bitirme Tarihi'),
        ),
        migrations.AddField(
            model_name='book',
            name='page_count',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Sayfa Sayısı'),
        ),
        migrations.AddField(
            model_name='book',
            name='rating',
            field=models.PositiveIntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True, verbose_name='Puan'),
        ),
        migrations.AddField(
            model_name='book',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Başlama Tarihi'),
        ),
    ]
